title: Roney Stones
email: roneylacerda@gmail.com
description: >
  Data + Design + Front-end. Em busca de uma internet mais rápida e acessível.
baseurl: ''
url: ''
twitter_username: roneystones
github_username: roneystones
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  add_charset: true
  sass_dir: assets/css
  style: ':compressed'
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
gems:
  - jekyll-feed
