title: Roney Stones
email: roneylacerda@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: roneystones
github_username: roneystones
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  add_charset: true
  sass_dir: assets/css
  style: ':compressed'
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-feed
