name:              Roney Stones
title:             Roney Stones
email:             roneylacerda@gmail.com
description:       Data + Design + Front-end. Em busca de uma internet mais rápida e acessível.

baseurl:           "" # the subpath of your site, e.g. /blog
url:               "http://roneystones.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink:         "/:categories/:title/" 

markdown: kramdown

include: 
  - _pages

exclude:
  - package.json
  - node_modules
  - gulpfile.js

plugins:
  - jekyll-minifier